Repository WildCodeSchool/2023-09-JS-Toulouse-666-Geocode, pull requests merged in 2024-01, with the labels that each got.

#11 feat: add charging station middleware, reservation middleware and use…
  backend/src/middlewares/validateChargingStation.js
  backend/src/middlewares/validateReservation.js
  backend/src/middlewares/validateUser.js
  backend/src/router.js
Labels: reviewed

#13 S2 us07/feat input
  backend/src/middlewares/validateUser.js
  backend/src/models/AbstractManager.js
  frontend/package-lock.json
  frontend/package.json
  frontend/src/assets/images/bckground.jpg
  frontend/src/components/form/form.jsx
  frontend/src/components/input/input.jsx
  frontend/src/components/input/input.scss
  frontend/src/components/select/select.jsx
  frontend/src/components/select/select.scss
  frontend/src/components/user/RegistrationPage/RegistrationForm.jsx
  frontend/src/components/user/RegistrationPage/RegistrationForm.scss
  frontend/src/components/user/RegistrationPage/config.json
  frontend/src/pages/ChargingStationManagement.jsx
Labels: reviewed

#15 S2 us7/map page
  frontend/package-lock.json
  frontend/package.json
  frontend/src/assets/el_map-marker.svg
  frontend/src/assets/tabler_location.svg
  frontend/src/components/map/location.jsx
  frontend/src/components/map/location.scss
  frontend/src/components/map/map.jsx
  frontend/src/components/map/map.scss
  frontend/src/components/map/search.jsx
  frontend/src/main.jsx
Labels: reviewed

#18 S2 us4/home page
  frontend/src/assets/images/Design-home.png
  frontend/src/assets/logoSearch.svg
  frontend/src/components/navbar/Navbar.jsx
  frontend/src/components/select/select.scss
  frontend/src/layout/RootLayout.jsx
  frontend/src/pages/Home.jsx
  frontend/src/pages/home.scss
  frontend/src/routes/AppRoutes.jsx
Labels: reviewed

#19 feat:add navbar
  frontend/src/components/logIn-Out/logInOut.jsx
  frontend/src/components/navbar/Navbar.jsx
  frontend/src/components/navbar/navbar.scss
  frontend/src/layout/RootLayout.jsx
  frontend/src/pages/home/Home.jsx
  frontend/src/pages/home/home.scss
  frontend/src/routes/AppRoutes.jsx
Labels: reviewed

#22 S2 us9/navbar
  frontend/src/assets/Vector.svg
  frontend/src/assets/avatar.png
  frontend/src/components/logIn-Out/logInOut.jsx
  frontend/src/components/logInOut/LogInOut.jsx
  frontend/src/components/logInOut/logInOut.scss
  frontend/src/components/navbar/Navbar.jsx
  frontend/src/components/navbar/navbar.scss
  frontend/src/contexte/CurrentUserContext.jsx
  frontend/src/layout/RootLayout.jsx
  frontend/src/pages/home/home.scss
Labels: reviewed

#23 S2 us8/login page
  backend/src/middlewares/validateUser.js
  backend/src/middlewares/validateUserLogin.js
  backend/src/router.js
  backend/src/services/auth.js
  frontend/.env.sample
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.css
  frontend/src/App.jsx
  frontend/src/assets/images/Hidden.png
  frontend/src/assets/images/Show.png
  frontend/src/assets/images/Vector.svg
  frontend/src/assets/images/email.png
  frontend/src/assets/images/password.png
  frontend/src/components/form/form.jsx
  frontend/src/components/input/input.jsx
  frontend/src/components/input/input.scss
  frontend/src/components/logInOut/LogInOut.jsx
  frontend/src/components/select/select.jsx
  frontend/src/components/select/select.scss
  frontend/src/components/user/ContactPage/ContactPage.jsx
  frontend/src/components/user/LoginPage/LoginPage.jsx
  frontend/src/components/user/LoginPage/login.scss
  frontend/src/components/user/RegistrationPage/RegistrationForm.jsx
  frontend/src/components/user/RegistrationPage/config.json
  frontend/src/contexte/CurrentUserContext.jsx
  frontend/src/pages/Logout.jsx
  frontend/src/pages/home/Home.jsx
  frontend/src/pages/home/home.scss
  frontend/src/reset.css
  frontend/src/routes/AppRoutes.jsx
  frontend/src/services/authVerify.js
Labels: reviewed, Correction done

#26 S3 us8/alert modal
  backend/src/controllers/userControllers.js
  frontend/index.html
  frontend/src/components/alert/alert.jsx
  frontend/src/components/alert/alert.scss
  frontend/src/components/navbar/Navbar.jsx
  frontend/src/components/user/ContactPage/ContactPage.jsx
  frontend/src/components/user/LoginPage/LoginPage.jsx
  frontend/src/components/user/LoginPage/login.scss
  frontend/src/components/user/RegistrationPage/RegistrationForm.jsx
  frontend/src/components/user/RegistrationPage/RegistrationForm.scss
Labels: reviewed

#29 S4 us10/feat admindashboard
  backend/src/models/userManager.js
  frontend/index.html
  frontend/src/assets/images/avatar.png
  frontend/src/assets/images/clarity_email-solid.svg
  frontend/src/assets/images/fa-solid_car.svg
  frontend/src/assets/images/fa-solid_users.svg
  frontend/src/assets/images/ion_settings.svg
  frontend/src/assets/images/solar_logout-2-bold.svg
  frontend/src/assets/images/uis_schedule.svg
  frontend/src/components/admin/table/SortableTable.jsx
  frontend/src/components/admin/table/TableBody.jsx
  frontend/src/components/admin/table/TableHeader.jsx
  frontend/src/components/admin/table/tableur.scss
  frontend/src/layout/AdminLayout.jsx
  frontend/src/layout/AdminLayout.scss
  frontend/src/pages/Logout.jsx
  frontend/src/pages/admin/CarsManagement.jsx
  frontend/src/pages/admin/DocumentManagement.jsx
  frontend/src/pages/admin/UserManagement.jsx
  frontend/src/routes/AppRoutes.jsx
  frontend/src/services/authVerify.js
Labels: reviewed, Correction done

#30 S3 us23/profil page
  backend/src/controllers/userControllers.js
  backend/src/models/userManager.js
  backend/src/router.js
  backend/tests/testdata.js
  frontend/src/components/navbar/Navbar.jsx
  frontend/src/components/navbar/navbar.scss
  frontend/src/components/profil/CardProfil.jsx
  frontend/src/components/profil/CartContent.jsx
  frontend/src/components/profil/Profil.jsx
  frontend/src/components/profil/profil.scss
  frontend/src/components/profile/CardProfile.jsx
  frontend/src/components/profile/CartContent.jsx
  frontend/src/components/profile/Profile.jsx
  frontend/src/components/profile/profile.scss
  frontend/src/routes/AppRoutes.jsx
Labels: Correction done

#31 S4 us10/feat admindashboard
  backend/src/router.js
  backend/src/services/auth.js
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/admin/table/TableBody.jsx
  frontend/src/components/admin/table/tableur.scss
  frontend/src/components/user/LoginPage/login.scss
  frontend/src/layout/AdminLayout.jsx
  frontend/src/layout/AdminLayout.scss
  frontend/src/pages/admin/UserManagement.jsx
  frontend/src/routes/AppRoutes.jsx
  frontend/src/services/authVerify.js
Labels: reviewed

#32 S2 us7/map page
  backend/package-lock.json
  backend/package.json
  backend/src/controllers/chargingStationControllers.js
  frontend/package-lock.json
  frontend/package.json
  frontend/src/assets/Deplier.svg
  frontend/src/assets/Prise1.svg
  frontend/src/assets/Prise2.svg
  frontend/src/assets/Prise3.svg
  frontend/src/assets/Prise4.svg
  frontend/src/assets/Prise5.svg
  frontend/src/assets/Replier.svg
  frontend/src/assets/lucide_plug.svg
  frontend/src/assets/mdi_clock-outline.svg
  frontend/src/components/map/itinerary.jsx
  frontend/src/components/map/location.scss
  frontend/src/components/map/map.jsx
  frontend/src/components/map/map.scss
  frontend/src/components/map/modal.jsx
  frontend/src/components/map/modal.scss
  frontend/src/components/map/search.jsx
  frontend/src/main.jsx
Labels: reviewed

#33 S4 us3/add car
  backend/src/controllers/brandControllers.js
  backend/src/controllers/plugControllers.js
  backend/src/models/AbstractManager.js
  backend/src/models/brandManager.js
  backend/src/models/plugManager.js
  backend/src/models/userManager.js
  backend/src/router.js
  backend/src/tables.js
  frontend/src/components/car/AddCar.jsx
  frontend/src/components/car/addCar.scss
  frontend/src/components/profile/CardProfile.jsx
  frontend/src/components/profile/CartContent.jsx
  frontend/src/components/profile/Profile.jsx
  frontend/src/routes/AppRoutes.jsx
Labels: reviewed, Correction done
