Repository WildCodeSchool/2023-09-JS-Toulouse-666-Geocode, pull requests merged in 2024-02, with the labels that each got.

#39 S4 us3/add car
  backend/src/controllers/carControllers.js
  backend/src/controllers/userControllers.js
  backend/src/models/carManager.js
  backend/src/models/userManager.js
  backend/src/router.js
  backend/tests/testdata.js
  frontend/src/assets/add_car.svg
  frontend/src/assets/croix.svg
  frontend/src/components/car/AddCar.jsx
  frontend/src/components/car/addCar.scss
  frontend/src/components/profile/CardPlug.jsx
  frontend/src/components/profile/CardProfile.jsx
  frontend/src/components/profile/CartContent.jsx
  frontend/src/components/profile/Profile.jsx
  frontend/src/components/profile/car/AddCar.jsx
  frontend/src/components/profile/car/CardCar.jsx
  frontend/src/components/profile/car/ModifyCar.jsx
  frontend/src/components/profile/profile.scss
  frontend/src/components/profile/user/CardProfile.jsx
  frontend/src/components/profile/user/ModyfyUser.jsx
  frontend/src/routes/AppRoutes.jsx
Labels: reviewed

#43 S5 us16/feat modal get location
  frontend/src/components/map/map.jsx
  frontend/src/components/map/modalLocationMap.scss
  frontend/src/components/map/search.jsx
  frontend/src/components/map/searchModal.jsx
Labels: reviewed

#46 S5 us1/reservation
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/map/map.jsx
  frontend/src/components/map/modalLocationMap.scss
  frontend/src/components/user/Reservation/Reservation.jsx
  frontend/src/components/user/Reservation/Reservation.scss
  frontend/src/components/user/Reservation/Schedule.jsx
  frontend/src/components/user/Reservation/Schedule.scss
Labels: reviewed

#47 S4 us3/add car
  backend/src/controllers/userControllers.js
  backend/src/models/userManager.js
  backend/src/router.js
  backend/src/services/auth.js
  frontend/src/components/navbar/navbar.scss
  frontend/src/components/profile/Profile.jsx
  frontend/src/components/profile/car/AddCar.jsx
  frontend/src/components/profile/car/CardCar.jsx
  frontend/src/components/profile/car/ModifyCar.jsx
  frontend/src/components/profile/profile.scss
  frontend/src/components/profile/user/CardProfile.jsx
  frontend/src/components/profile/user/ModyfyUser.jsx
Labels: Changes requested, reviewed

#48 S5 us1/reservation
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/map/map.jsx
  frontend/src/components/map/modal.jsx
  frontend/src/components/map/modal.scss
  frontend/src/components/map/modalLocationMap.scss
  frontend/src/components/profile/profile.scss
  frontend/src/components/user/Reservation/Reservation.jsx
  frontend/src/components/user/Reservation/Reservation.scss
  frontend/src/components/user/Reservation/Schedule.scss
Labels: reviewed

#49 S4 us3/add car
  backend/src/controllers/reservationControllers.js
  backend/src/models/ReservationManager.js
  backend/src/router.js
  frontend/src/components/profile/CardPlug.jsx
  frontend/src/components/profile/profile.scss
Labels: reviewed

#50 S4 us3/add car
  frontend/src/assets/hiddem.svg
  frontend/src/assets/show.svg
  frontend/src/components/map/map.jsx
  frontend/src/components/navbar/Navbar.jsx
  frontend/src/components/profile/profile.scss
  frontend/src/components/profile/user/ModyfyUser.jsx
Labels: reviewed

#51 S5 us1/reservation
  frontend/src/assets/Geocode.svg
  frontend/src/components/logInOut/logInOut.scss
  frontend/src/components/map/itinerary.scss
  frontend/src/components/map/map.scss
  frontend/src/components/map/modal.jsx
  frontend/src/components/map/modal.scss
  frontend/src/components/user/Reservation/Reservation.jsx
  frontend/src/components/user/Reservation/Reservation.scss
  frontend/src/pages/home/Home.jsx
  frontend/src/pages/home/home.scss
Labels: reviewed

#52 S5 us16/feat modal get location
  backend/src/controllers/userControllers.js
  backend/src/models/ReservationManager.js
  backend/src/models/userManager.js
  backend/src/router.js
  backend/src/services/auth.js
  frontend/src/assets/images/backgrounddesktop.png
  frontend/src/assets/images/clarity_home-solid.png
  frontend/src/assets/imagesvoitures/Revolte-Zoe.png
  frontend/src/assets/imagesvoitures/audi-e-tron-gt-476.png
  frontend/src/assets/imagesvoitures/default.png
  frontend/src/assets/imagesvoitures/fiat-500-e-95.png
  frontend/src/assets/imagesvoitures/mini-cooper-se-184ch.png
  frontend/src/assets/imagesvoitures/peugeot-e-208-electrique-50-kwh-136ch.png
  frontend/src/assets/imagesvoitures/tesla-model-3.png
  frontend/src/components/alert/alert.jsx
  frontend/src/components/profile/CardPlug.jsx
  frontend/src/components/profile/Profile.jsx
  frontend/src/components/profile/car/CardCar.jsx
  frontend/src/components/profile/car/images.js
  frontend/src/components/profile/profile.scss
  frontend/src/components/user/LoginPage/LoginPage.jsx
  frontend/src/components/user/RegistrationPage/RegistrationForm.scss
  frontend/src/layout/AdminLayout.jsx
  frontend/src/layout/AdminLayout.scss
  frontend/src/layout/RootLayout.jsx
  frontend/src/services/authVerify.js
Labels: reviewed, Correction done

#53 S4 us3/add car
  frontend/src/components/map/map.jsx
  frontend/src/components/profile/user/CardProfile.jsx
  frontend/src/reset.css
Labels: reviewed

#55 S6 us17/fix style
  frontend/src/assets/fonts/MADE Future X Black PERSONAL USE.otf
  frontend/src/assets/fonts/MADE Future X Bold PERSONAL USE.otf
  frontend/src/assets/fonts/MADE Future X HEADER Black PERSONAL USE.otf
  frontend/src/assets/fonts/MADE Future X HEADER Bold PERSONAL.otf
  frontend/src/assets/fonts/MADE Future X HEADER Light PERSONAL USE.otf
  frontend/src/assets/fonts/MADE Future X HEADER Line PERSONAL USE.otf
  frontend/src/assets/fonts/MADE Future X HEADER Medium PERSONAL USE.otf
  frontend/src/assets/fonts/MADE Future X HEADER Regular PERSONAL USE.otf
  frontend/src/assets/fonts/MADE Future X HEADER Thin PERSONAL USE.otf
  frontend/src/assets/fonts/MADE Future X Light PERSONAL USE.otf
  frontend/src/assets/fonts/MADE Future X Line PERSONAL USE.otf
  frontend/src/assets/fonts/MADE Future X Medium PERSONAL USE.otf
  frontend/src/assets/fonts/MADE Future X Regular PERSONAL USE.otf
  frontend/src/assets/fonts/MADE Future X Thin PERSONAL USE.otf
  frontend/src/components/map/modal.scss
  frontend/src/components/profile/profile.scss
  frontend/src/components/user/RegistrationPage/RegistrationForm.jsx
  frontend/src/components/user/Reservation/Reservation.jsx
  frontend/src/components/user/Reservation/Reservation.scss
  frontend/src/layout/AdminLayout.jsx
  frontend/src/layout/root.scss
  frontend/src/reset.css
  frontend/src/services/authVerify.js
Labels: reviewed

#63 S6 us21/refactor profile page
  backend/public/assets/fonts/MADEFutureXLightPERSONALUSE.otf
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/profile/Profile.jsx
  frontend/src/components/profile/car/AddCar.jsx
  frontend/src/components/profile/profile.scss
  frontend/src/components/profile/user/ModyfyUser.jsx
  frontend/src/pages/home/home.scss
  frontend/src/reset.css
Labels: reviewed
